apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: zkp38v2-m-go 
  janus-idp.io/tekton: zkp38v2-m-go
  backstage.io/kubernetes-id: zkp38v2-m-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: zkp38v2-m-go
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  