apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: zkp38v2-m-go
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/rhtap-qe:c9da80be6f45f61c10f3843e7310ab69223d1e78@sha256:0b86b5bbfecea865d67ed7967beaf8a924b1768f158a28b4448134b73bab74bc
          name: container-image
